### ISSUE TITLE
Protect 'search (sr)' when search executable can not be found

### ISSUE THREAD

**Issue by trevorbaca** [Abjad/ide#108]
On a new machine:
```
Ikribu (2016) - action commands

    edit every file (ff*)

    display action command help (?)
    invoke shell (!)
    refresh (rf)
    replace (rp)
    search (sr)

    aliases - edit (als)
    latex log - edit (lxg)
    lilypond log - edit (lpg)

    doctest - run (dt)
    pytest - run (pt)

    score pdf - open (so)

    git - commit (ci)
    git - status (st)
    git - update (up)

> sr

Traceback (most recent call last):
  File "/Users/trevorbaca/Documents/abjad-ide/ide/scr/start-abjad-ide", line 8, in <module>
    abjad_ide._start(input_=input_)
  File "/Users/trevorbaca/Documents/abjad-ide/ide/tools/idetools/AbjadIDE.py", line 2018, in _start
    self._manage_directory(directory)
  File "/Users/trevorbaca/Documents/abjad-ide/ide/tools/idetools/AbjadIDE.py", line 1641, in _manage_directory
    self._handle_input(result)
  File "/Users/trevorbaca/Documents/abjad-ide/ide/tools/idetools/AbjadIDE.py", line 756, in _handle_input
    self._manage_directory(result)
  File "/Users/trevorbaca/Documents/abjad-ide/ide/tools/idetools/AbjadIDE.py", line 1641, in _manage_directory
    self._handle_input(result)
  File "/Users/trevorbaca/Documents/abjad-ide/ide/tools/idetools/AbjadIDE.py", line 736, in _handle_input
    self._manage_directory(path)
  File "/Users/trevorbaca/Documents/abjad-ide/ide/tools/idetools/AbjadIDE.py", line 1641, in _manage_directory
    self._handle_input(result)
  File "/Users/trevorbaca/Documents/abjad-ide/ide/tools/idetools/AbjadIDE.py", line 736, in _handle_input
    self._manage_directory(path)
  File "/Users/trevorbaca/Documents/abjad-ide/ide/tools/idetools/AbjadIDE.py", line 1641, in _manage_directory
    self._handle_input(result)
  File "/Users/trevorbaca/Documents/abjad-ide/ide/tools/idetools/AbjadIDE.py", line 748, in _handle_input
    command()
  File "/Users/trevorbaca/Documents/abjad-ide/ide/tools/idetools/AbjadIDE.py", line 3315, in go_back
    self._manage_directory(directory)
  File "/Users/trevorbaca/Documents/abjad-ide/ide/tools/idetools/AbjadIDE.py", line 1641, in _manage_directory
    self._handle_input(result)
  File "/Users/trevorbaca/Documents/abjad-ide/ide/tools/idetools/AbjadIDE.py", line 736, in _handle_input
    self._manage_directory(path)
  File "/Users/trevorbaca/Documents/abjad-ide/ide/tools/idetools/AbjadIDE.py", line 1641, in _manage_directory
    self._handle_input(result)
  File "/Users/trevorbaca/Documents/abjad-ide/ide/tools/idetools/AbjadIDE.py", line 746, in _handle_input
    command(self._session.current_directory)
  File "/Users/trevorbaca/Documents/abjad-ide/ide/tools/idetools/AbjadIDE.py", line 3431, in go_to_score_directory
    self._manage_directory(directory)
  File "/Users/trevorbaca/Documents/abjad-ide/ide/tools/idetools/AbjadIDE.py", line 1641, in _manage_directory
    self._handle_input(result)
  File "/Users/trevorbaca/Documents/abjad-ide/ide/tools/idetools/AbjadIDE.py", line 746, in _handle_input
    command(self._session.current_directory)
  File "/Users/trevorbaca/Documents/abjad-ide/ide/tools/idetools/AbjadIDE.py", line 4256, in search
    assert len(executable) == 1
AssertionError
```

Probably because ack is installed somewhere the IDE can not find.

IDE should never dump stack; better to print "search executable can not be found" and return control to the user.

**Comment by trevorbaca** [comment]
Closed with PR #109.
