### ISSUE TITLE
Handle unknown paper sizes gracefully

### ISSUE THREAD

**Issue by trevorbaca** [Abjad/ide#161]
```
Mráz (2017) - build directory

      copy (cp)
      new (new)
      remove (rm)
      rename (ren)

> new
Subdirectory name]> arch_e
Paper size (ex: letter or letter landscape)]> ARCH-E
Price (ex: \$80 / \euro 72)]> \$29 / \euro 22
Catalog number suffix (ex: ann.)]> 
Will create ...
   mraz/mraz/build/arch-e
   mraz/mraz/build/arch-e/back-cover.tex
   mraz/mraz/build/arch-e/front-cover.tex
   mraz/mraz/build/arch-e/music.ly
   mraz/mraz/build/arch-e/preface.tex
   mraz/mraz/build/arch-e/score.tex
   mraz/mraz/build/arch-e/stylesheet.ily
Ok? y

Traceback (most recent call last):
  File "/Users/trevorbaca/abjad-ide/ide/scr/start-abjad-ide", line 8, in <module>
    abjad_ide._start(input_=input_)
  File "/Users/trevorbaca/abjad-ide/ide/tools/idetools/AbjadIDE.py", line 2401, in _start
    self._manage_directory(directory)
  File "/Users/trevorbaca/abjad-ide/ide/tools/idetools/AbjadIDE.py", line 1929, in _manage_directory
    self._handle_input(result)
  File "/Users/trevorbaca/abjad-ide/ide/tools/idetools/AbjadIDE.py", line 876, in _handle_input
    self._manage_directory(result)
  File "/Users/trevorbaca/abjad-ide/ide/tools/idetools/AbjadIDE.py", line 1929, in _manage_directory
    self._handle_input(result)
  File "/Users/trevorbaca/abjad-ide/ide/tools/idetools/AbjadIDE.py", line 866, in _handle_input
    command(self._session.current_directory)
  File "/Users/trevorbaca/abjad-ide/ide/tools/idetools/AbjadIDE.py", line 4119, in go_to_tools_directory
    self._manage_directory(directory)
  File "/Users/trevorbaca/abjad-ide/ide/tools/idetools/AbjadIDE.py", line 1929, in _manage_directory
    self._handle_input(result)
  File "/Users/trevorbaca/abjad-ide/ide/tools/idetools/AbjadIDE.py", line 868, in _handle_input
    command()
  File "/Users/trevorbaca/abjad-ide/ide/tools/idetools/AbjadIDE.py", line 3928, in go_back
    self._manage_directory(directory)
  File "/Users/trevorbaca/abjad-ide/ide/tools/idetools/AbjadIDE.py", line 1929, in _manage_directory
    self._handle_input(result)
  File "/Users/trevorbaca/abjad-ide/ide/tools/idetools/AbjadIDE.py", line 868, in _handle_input
    command()
  File "/Users/trevorbaca/abjad-ide/ide/tools/idetools/AbjadIDE.py", line 3939, in go_home
    self._manage_directory(directory)
  File "/Users/trevorbaca/abjad-ide/ide/tools/idetools/AbjadIDE.py", line 1929, in _manage_directory
    self._handle_input(result)
  File "/Users/trevorbaca/abjad-ide/ide/tools/idetools/AbjadIDE.py", line 876, in _handle_input
    self._manage_directory(result)
  File "/Users/trevorbaca/abjad-ide/ide/tools/idetools/AbjadIDE.py", line 1929, in _manage_directory
    self._handle_input(result)
  File "/Users/trevorbaca/abjad-ide/ide/tools/idetools/AbjadIDE.py", line 866, in _handle_input
    command(self._session.current_directory)
  File "/Users/trevorbaca/abjad-ide/ide/tools/idetools/AbjadIDE.py", line 4119, in go_to_tools_directory
    self._manage_directory(directory)
  File "/Users/trevorbaca/abjad-ide/ide/tools/idetools/AbjadIDE.py", line 1929, in _manage_directory
    self._handle_input(result)
  File "/Users/trevorbaca/abjad-ide/ide/tools/idetools/AbjadIDE.py", line 866, in _handle_input
    command(self._session.current_directory)
  File "/Users/trevorbaca/abjad-ide/ide/tools/idetools/AbjadIDE.py", line 4044, in go_to_score_directory
    self._manage_directory(directory)
  File "/Users/trevorbaca/abjad-ide/ide/tools/idetools/AbjadIDE.py", line 1929, in _manage_directory
    self._handle_input(result)
  File "/Users/trevorbaca/abjad-ide/ide/tools/idetools/AbjadIDE.py", line 868, in _handle_input
    command()
  File "/Users/trevorbaca/abjad-ide/ide/tools/idetools/AbjadIDE.py", line 3939, in go_home
    self._manage_directory(directory)
  File "/Users/trevorbaca/abjad-ide/ide/tools/idetools/AbjadIDE.py", line 1929, in _manage_directory
    self._handle_input(result)
  File "/Users/trevorbaca/abjad-ide/ide/tools/idetools/AbjadIDE.py", line 876, in _handle_input
    self._manage_directory(result)
  File "/Users/trevorbaca/abjad-ide/ide/tools/idetools/AbjadIDE.py", line 1929, in _manage_directory
    self._handle_input(result)
  File "/Users/trevorbaca/abjad-ide/ide/tools/idetools/AbjadIDE.py", line 830, in _handle_input
    self._manage_directory(path)
  File "/Users/trevorbaca/abjad-ide/ide/tools/idetools/AbjadIDE.py", line 1929, in _manage_directory
    self._handle_input(result)
  File "/Users/trevorbaca/abjad-ide/ide/tools/idetools/AbjadIDE.py", line 866, in _handle_input
    command(self._session.current_directory)
  File "/Users/trevorbaca/abjad-ide/ide/tools/idetools/AbjadIDE.py", line 3954, in go_to_build_directory
    self._manage_directory(directory)
  File "/Users/trevorbaca/abjad-ide/ide/tools/idetools/AbjadIDE.py", line 1929, in _manage_directory
    self._handle_input(result)
  File "/Users/trevorbaca/abjad-ide/ide/tools/idetools/AbjadIDE.py", line 866, in _handle_input
    command(self._session.current_directory)
  File "/Users/trevorbaca/abjad-ide/ide/tools/idetools/AbjadIDE.py", line 4466, in new
    self._make_build_subdirectory(directory)
  File "/Users/trevorbaca/abjad-ide/ide/tools/idetools/AbjadIDE.py", line 1270, in _make_build_subdirectory
    self.generate_back_cover_source(build_subdirectory)
  File "/Users/trevorbaca/abjad-ide/ide/tools/idetools/AbjadIDE.py", line 3328, in generate_back_cover_source
    paper_size = self._to_paper_dimensions(paper_size, orientation)
  File "/Users/trevorbaca/abjad-ide/ide/tools/idetools/AbjadIDE.py", line 3438, in _to_paper_dimensions
    paper_dimensions = self._paper_size_to_paper_dimensions[paper_size]
KeyError: 'ARCH-E'
```

**Comment by trevorbaca** [comment]
Defaulted paper size to US letter.
