### ISSUE TITLE
Make (ren) work in external directories

### ISSUE THREAD

**Issue by trevorbaca** [Abjad/ide#165]
```
> ren
Traceback (most recent call last):
  File "/Users/trevorbaca/abjad-ide/ide/scr/start-abjad-ide", line 8, in <module>
    abjad_ide._start(input_=input_)
  File "/Users/trevorbaca/abjad-ide/ide/tools/idetools/AbjadIDE.py", line 2401, in _start
    self._manage_directory(directory)
  File "/Users/trevorbaca/abjad-ide/ide/tools/idetools/AbjadIDE.py", line 1917, in _manage_directory
    self._manage_directory(path)
  File "/Users/trevorbaca/abjad-ide/ide/tools/idetools/AbjadIDE.py", line 1929, in _manage_directory
    self._handle_input(result)
  File "/Users/trevorbaca/abjad-ide/ide/tools/idetools/AbjadIDE.py", line 866, in _handle_input
    command(self._session.current_directory)
  File "/Users/trevorbaca/abjad-ide/ide/tools/idetools/AbjadIDE.py", line 4762, in rename
    source_path = self._select_visible_path(directory, 'to rename')
  File "/Users/trevorbaca/abjad-ide/ide/tools/idetools/AbjadIDE.py", line 2322, in _select_visible_path
    asset_identifier = self._to_asset_identifier(directory)
  File "/Users/trevorbaca/abjad-ide/ide/tools/idetools/AbjadIDE.py", line 2453, in _to_asset_identifier
    raise ValueError(directory)
ValueError: /Users/trevorbaca/baca/baca/tools
```

**Comment by trevorbaca** [comment]
Done.
