### ISSUE TITLE
Manage external directories

### ISSUE THREAD

**Issue by trevorbaca** [Abjad/ide#168]
```
> cdsd
Traceback (most recent call last):
  File "/Users/trevorbaca/abjad-ide/ide/scr/start-abjad-ide", line 8, in <module>
    abjad_ide._start(input_=input_)
  File "/Users/trevorbaca/abjad-ide/ide/tools/idetools/AbjadIDE.py", line 2402, in _start
    self._manage_directory(directory)
  File "/Users/trevorbaca/abjad-ide/ide/tools/idetools/AbjadIDE.py", line 1930, in _manage_directory
    self._handle_input(result)
  File "/Users/trevorbaca/abjad-ide/ide/tools/idetools/AbjadIDE.py", line 876, in _handle_input
    self._manage_directory(result)
  File "/Users/trevorbaca/abjad-ide/ide/tools/idetools/AbjadIDE.py", line 1930, in _manage_directory
    self._handle_input(result)
  File "/Users/trevorbaca/abjad-ide/ide/tools/idetools/AbjadIDE.py", line 830, in _handle_input
    self._manage_directory(path)
  File "/Users/trevorbaca/abjad-ide/ide/tools/idetools/AbjadIDE.py", line 1918, in _manage_directory
    self._manage_directory(path)
  File "/Users/trevorbaca/abjad-ide/ide/tools/idetools/AbjadIDE.py", line 1930, in _manage_directory
    self._handle_input(result)
  File "/Users/trevorbaca/abjad-ide/ide/tools/idetools/AbjadIDE.py", line 868, in _handle_input
    command()
  File "/Users/trevorbaca/abjad-ide/ide/tools/idetools/AbjadIDE.py", line 3929, in go_back
    self._manage_directory(directory)
  File "/Users/trevorbaca/abjad-ide/ide/tools/idetools/AbjadIDE.py", line 1918, in _manage_directory
    self._manage_directory(path)
  File "/Users/trevorbaca/abjad-ide/ide/tools/idetools/AbjadIDE.py", line 1930, in _manage_directory
    self._handle_input(result)
  File "/Users/trevorbaca/abjad-ide/ide/tools/idetools/AbjadIDE.py", line 868, in _handle_input
    command()
  File "/Users/trevorbaca/abjad-ide/ide/tools/idetools/AbjadIDE.py", line 3929, in go_back
    self._manage_directory(directory)
  File "/Users/trevorbaca/abjad-ide/ide/tools/idetools/AbjadIDE.py", line 1918, in _manage_directory
    self._manage_directory(path)
  File "/Users/trevorbaca/abjad-ide/ide/tools/idetools/AbjadIDE.py", line 1930, in _manage_directory
    self._handle_input(result)
  File "/Users/trevorbaca/abjad-ide/ide/tools/idetools/AbjadIDE.py", line 868, in _handle_input
    command()
  File "/Users/trevorbaca/abjad-ide/ide/tools/idetools/AbjadIDE.py", line 3929, in go_back
    self._manage_directory(directory)
  File "/Users/trevorbaca/abjad-ide/ide/tools/idetools/AbjadIDE.py", line 1918, in _manage_directory
    self._manage_directory(path)
  File "/Users/trevorbaca/abjad-ide/ide/tools/idetools/AbjadIDE.py", line 1918, in _manage_directory
    self._manage_directory(path)
  File "/Users/trevorbaca/abjad-ide/ide/tools/idetools/AbjadIDE.py", line 1886, in _manage_directory
    menu_header = self._to_menu_header(directory)
  File "/Users/trevorbaca/abjad-ide/ide/tools/idetools/AbjadIDE.py", line 2494, in _to_menu_header
    score_part = self._get_title_metadatum(score_directory)
  File "/Users/trevorbaca/abjad-ide/ide/tools/idetools/AbjadIDE.py", line 697, in _get_title_metadatum
    if year and self._get_metadatum(score_directory, 'year'):
  File "/Users/trevorbaca/abjad-ide/ide/tools/idetools/AbjadIDE.py", line 603, in _get_metadatum
    assert os.path.isdir(directory), repr(directory)
AssertionError: '/Users/trevorbaca/Scores/_docs/_docs'
```

**Comment by trevorbaca** [comment]
No longer crashes but should list directory:
```
(untitled score) - wrapper directory

      copy (cp)
      new (new)
      remove (rm)
      rename (ren)

> !pwd
/Users/trevorbaca/Scores/_docs

``

**Comment by trevorbaca** [comment]
```
Abjad IDE - /Users/trevorbaca/Scores/_docs

   1: Makefile
   2: build
   3: make.bat
   4: make_baca_api.py
   5: source

      copy (cp)
      new (new)
      remove (rm)
      rename (ren)

> 
```

**Comment by trevorbaca** [comment]
Done.
