### ISSUE TITLE
Make (rm) work in external directories

### ISSUE THREAD

**Issue by trevorbaca** [Abjad/ide#170]
Reproduce with (baca > rm):
```
  94: WellformednessManager.py
  95: WrapLibrary.py
  96: ZaggedPitchClassMaker.py
  97: increase_elements.py
  98: iterate_sequence_boustrophedon.py
  99: negate_elements.py
 100: overwrite_elements.py
 101: partition_sequence_by_sign_of_elements.py

      copy (cp)
      new (new)
      remove (rm)
      rename (ren)

> rm
Traceback (most recent call last):
  File "/Users/trevorbaca/abjad-ide/ide/scr/start-abjad-ide", line 8, in <module>
    abjad_ide._start(input_=input_)
  File "/Users/trevorbaca/abjad-ide/ide/tools/idetools/AbjadIDE.py", line 2400, in _start
    self._manage_directory(directory)
  File "/Users/trevorbaca/abjad-ide/ide/tools/idetools/AbjadIDE.py", line 1918, in _manage_directory
    self._manage_directory(path)
  File "/Users/trevorbaca/abjad-ide/ide/tools/idetools/AbjadIDE.py", line 1930, in _manage_directory
    self._handle_input(result)
  File "/Users/trevorbaca/abjad-ide/ide/tools/idetools/AbjadIDE.py", line 866, in _handle_input
    command(self._session.current_directory)
  File "/Users/trevorbaca/abjad-ide/ide/tools/idetools/AbjadIDE.py", line 4694, in remove
    paths = self._select_visible_paths(directory, 'to remove')
  File "/Users/trevorbaca/abjad-ide/ide/tools/idetools/AbjadIDE.py", line 2345, in _select_visible_paths
    asset_identifier = self._to_asset_identifier(directory)
  File "/Users/trevorbaca/abjad-ide/ide/tools/idetools/AbjadIDE.py", line 2452, in _to_asset_identifier
    raise ValueError(directory)
ValueError: /Users/trevorbaca/baca/baca/tools
```

**Comment by trevorbaca** [comment]
Done.
