### ISSUE TITLE
Match asset numbers instead of segment numbers

### ISSUE THREAD

**Issue by trevorbaca** [Abjad/ide#231]
- [x] Never match segment numbers
- [x] Allow single-letter uppercase segment directory names
- [x] Harmonize score segments to letters
- [x] Match asset numbers:
```
  51: test_AbjadIDE_go_to_distribution_directory.py    103: test_Path_match_path
  52: test_AbjadIDE_go_to_etc_directory.py             104: test_idetools___doc_

> ^52
Traceback (most recent call last):
  File "/Users/trevorbaca/abjad-ide/ide/scr/start-abjad-ide", line 18, in <module>
    abjad_ide(string)
  File "/Users/trevorbaca/abjad-ide/ide/tools/idetools/AbjadIDE.py", line 98, in __call__
    self._manage_directory(scores)
  File "/Users/trevorbaca/abjad-ide/ide/tools/idetools/AbjadIDE.py", line 795, in _manage_directory
    self._manage_directory(path)
  File "/Users/trevorbaca/abjad-ide/ide/tools/idetools/AbjadIDE.py", line 795, in _manage_directory
    self._manage_directory(path)
  File "/Users/trevorbaca/abjad-ide/ide/tools/idetools/AbjadIDE.py", line 818, in _manage_directory
    self._manage_directory(self.current_directory, redraw=redraw)
  File "/Users/trevorbaca/abjad-ide/ide/tools/idetools/AbjadIDE.py", line 818, in _manage_directory
    self._manage_directory(self.current_directory, redraw=redraw)
  File "/Users/trevorbaca/abjad-ide/ide/tools/idetools/AbjadIDE.py", line 818, in _manage_directory
    self._manage_directory(self.current_directory, redraw=redraw)
  File "/Users/trevorbaca/abjad-ide/ide/tools/idetools/AbjadIDE.py", line 795, in _manage_directory
    self._manage_directory(path)
  File "/Users/trevorbaca/abjad-ide/ide/tools/idetools/AbjadIDE.py", line 818, in _manage_directory
    self._manage_directory(self.current_directory, redraw=redraw)
  File "/Users/trevorbaca/abjad-ide/ide/tools/idetools/AbjadIDE.py", line 818, in _manage_directory
    self._manage_directory(self.current_directory, redraw=redraw)
  File "/Users/trevorbaca/abjad-ide/ide/tools/idetools/AbjadIDE.py", line 818, in _manage_directory
    self._manage_directory(self.current_directory, redraw=redraw)
  [Previous line repeated 6 more times]
  File "/Users/trevorbaca/abjad-ide/ide/tools/idetools/AbjadIDE.py", line 795, in _manage_directory
    self._manage_directory(path)
  File "/Users/trevorbaca/abjad-ide/ide/tools/idetools/AbjadIDE.py", line 818, in _manage_directory
    self._manage_directory(self.current_directory, redraw=redraw)
  File "/Users/trevorbaca/abjad-ide/ide/tools/idetools/AbjadIDE.py", line 814, in _manage_directory
    command()
  File "/Users/trevorbaca/abjad-ide/ide/tools/idetools/AbjadIDE.py", line 2405, in go_to_library
    self._manage_directory(Path(library))
  File "/Users/trevorbaca/abjad-ide/ide/tools/idetools/AbjadIDE.py", line 818, in _manage_directory
    self._manage_directory(self.current_directory, redraw=redraw)
  File "/Users/trevorbaca/abjad-ide/ide/tools/idetools/AbjadIDE.py", line 795, in _manage_directory
    self._manage_directory(path)
  File "/Users/trevorbaca/abjad-ide/ide/tools/idetools/AbjadIDE.py", line 795, in _manage_directory
    self._manage_directory(path)
  File "/Users/trevorbaca/abjad-ide/ide/tools/idetools/AbjadIDE.py", line 759, in _manage_directory
    paths = directory.match_paths(*response.pair)
  File "/Users/trevorbaca/abjad-ide/ide/tools/idetools/Path.py", line 239, in match_paths
    path = self.segment_number_to_path(segment_number)
  File "/Users/trevorbaca/abjad/abjad/tools/datastructuretools/Path.py", line 1579, in segment_number_to_path
    for path in self.segments().glob('*'):
AttributeError: 'NoneType' object has no attribute 'glob'
```
- [x] Write `@1` test
- [x] Write `%1` test
- [x] Write `^1` test
- [x] Write `*1` test
- [x] Write `+1` test
- [x] Fix:
```
Abjad IDE : scores

      __metadata__.py

   1: Akasha (2015)                         13: Lidércfény (2008)
   2: Aklın hazine odasına (incomplete)     14: L'imaginare (2010)
   3: Al-kitab al-khamr (2015)              15: Manifolds (incomplete)
   4: Betörung (incomplete)                 16: Mon seul désir (2009)
   5: Čáry (2006)                           17: Mráz (2017)
   6: Fabergé Investigations (2016)         18: Myrkr (2015)
   7: Huitzil (2014)                        19: Poème récursif (2003)
   8: Ikribu (2016)                         20: Red Shift Hijinks (2006)
   9: Ins Wasser eingeschrieben (2014)      21: Sekka (2007)
  10: Krummzeit (2014)                      22: Spiel der Dornen (2016)
  11: L'archipel du corps (2011)            23: Stirrings Still (2017)
  12: Las manos mágicas (incomplete)        24: Traiettorie inargentate (2013)

> red shift
Traceback (most recent call last):
  File "/Users/trevorbaca/abjad-ide/ide/scr/start-abjad-ide", line 18, in <module>
    abjad_ide(string)
  File "/Users/trevorbaca/abjad-ide/ide/tools/idetools/AbjadIDE.py", line 99, in __call__
    self._manage_directory(scores)
  File "/Users/trevorbaca/abjad-ide/ide/tools/idetools/AbjadIDE.py", line 833, in _manage_directory
    raise Exception(response)
Exception: Response(payload=[Path('/Users/trevorbaca/Scores/hijinks')], source='asset', string='red')
```
- [x] remove `in score ...` messaging

**Comment by trevorbaca** [comment]
Done.
