### ISSUE TITLE
Make sure commands are available only on the screens that they should be

### ISSUE THREAD

**Issue by trevorbaca** [Abjad/ide#67]
You can, for example, currently call (s) at the main screen, which makes no sense (and raises an exception):
```
Abjad IDE - all score directories

   1. Red Example Score
   2. Blue Example Score

      copy (cp)
      new (new)
      remove (rm)
      rename (ren)

> s
Traceback (most recent call last):
  File "/Users/trevorbaca/Documents/ide/ide/scr/start-abjad-ide", line 5, in <module>
    ide.tools.idetools.AbjadIDE.start_abjad_ide()
  File "/Users/trevorbaca/Documents/ide/ide/tools/idetools/AbjadIDE.py", line 4671, in start_abjad_ide
    abjad_ide._run_main_menu(input_=input_)
  File "/Users/trevorbaca/Documents/ide/ide/tools/idetools/AbjadIDE.py", line 2169, in _run_main_menu
    self._run_wrangler_menu('scores')
  File "/Users/trevorbaca/Documents/ide/ide/tools/idetools/AbjadIDE.py", line 2237, in _run_wrangler_menu
    self._handle_input(result, directory_name=directory_name)
  File "/Users/trevorbaca/Documents/ide/ide/tools/idetools/AbjadIDE.py", line 1052, in _handle_input
    command(_path)
  File "/Users/trevorbaca/Documents/ide/ide/tools/idetools/AbjadIDE.py", line 3879, in go_to_score_directory
    self._run_package_manager_menu(current_score_directory)
  File "/Users/trevorbaca/Documents/ide/ide/tools/idetools/AbjadIDE.py", line 2175, in _run_package_manager_menu
    assert os.path.sep in directory, repr(directory)
TypeError: argument of type 'NoneType' is not iterable
```

**Comment by trevorbaca** [comment]
Done 2015-09-15.
