### ISSUE TITLE
Fix (rm) error

### ISSUE THREAD

**Issue by trevorbaca** [Abjad/ide#8]
Stack trace:
```
> rm 15, 16, 17, 19, 20, 21, 24, 25
Enter makers(s) to remove]> 15, 16, 17, 19, 20, 21, 24, 25
Will remove ...
    /Users/trevorbaca/Documents/scores/krummzeit/krummzeit/makers/ColorFingeringSpecifier.py
    /Users/trevorbaca/Documents/scores/krummzeit/krummzeit/makers/GlissandoSpecifier.py
    /Users/trevorbaca/Documents/scores/krummzeit/krummzeit/makers/MicrotonalDeviationSpecifier.py
    /Users/trevorbaca/Documents/scores/krummzeit/krummzeit/makers/PitchSpecifier.py
    /Users/trevorbaca/Documents/scores/krummzeit/krummzeit/makers/RegistrationSpecifier.py
    /Users/trevorbaca/Documents/scores/krummzeit/krummzeit/makers/RegistrationTransitionSpecifier.py
    /Users/trevorbaca/Documents/scores/krummzeit/krummzeit/makers/StemTremoloSpecifier.py
    /Users/trevorbaca/Documents/scores/krummzeit/krummzeit/makers/TrillSpecifier.py
Type 'remove 8' to proceed]> remove 8
Traceback (most recent call last):
  File "/Users/trevorbaca/Documents/ide/ide/scr/start-abjad-ide", line 4, in <module>
    ide.idetools.start_abjad_ide()
  File "/Users/trevorbaca/Documents/ide/ide/idetools/start_abjad_ide.py", line 13, in start_abjad_ide
    abjad_ide._run(input_=input_)
  File "/Users/trevorbaca/Documents/ide/ide/idetools/AbjadIDE.py", line 216, in _run
    result)
  File "/Users/trevorbaca/Documents/ide/ide/idetools/AssetController.py", line 237, in _handle_input
    self._command_to_method[result]()
  File "/Users/trevorbaca/Documents/ide/ide/idetools/AssetController.py", line 759, in go_to_score_maker_files
    self._session._abjad_ide._maker_file_wrangler._run()
  File "/Users/trevorbaca/Documents/ide/ide/idetools/Wrangler.py", line 812, in _run
    self._handle_input(result)
  File "/Users/trevorbaca/Documents/ide/ide/idetools/AssetController.py", line 237, in _handle_input
    self._command_to_method[result]()
  File "/Users/trevorbaca/Documents/ide/ide/idetools/FileWrangler.py", line 147, in remove_files
    self._remove_assets()
  File "/Users/trevorbaca/Documents/ide/ide/idetools/Wrangler.py", line 764, in _remove_assets
    manager._remove()
  File "/Users/trevorbaca/Documents/ide/ide/idetools/PackageManager.py", line 661, in _remove
    with systemtools.TemporaryDirectoryChange(directory=self._path):
  File "/Users/trevorbaca/Documents/abjad/abjad/tools/systemtools/TemporaryDirectoryChange.py", line 29, in __enter__
    os.chdir(self.directory)
OSError: [Errno 2] No such file or directory: '/Users/trevorbaca/Documents/scores/krummzeit/krummzeit/makers/ColorFingeringSpecifier.py'
```

**Comment by trevorbaca** [comment]
Also shows up on removing a single maker:
```
> rm 15
Enter makers(s) to remove]> 15
Will remove /Users/trevorbaca/Documents/scores/krummzeit/krummzeit/makers/GlissandoSpecifier.py
Type 'remove' to proceed]> remove
Traceback (most recent call last):
  File "/Users/trevorbaca/Documents/ide/ide/scr/start-abjad-ide", line 4, in <module>
    ide.idetools.start_abjad_ide()
  File "/Users/trevorbaca/Documents/ide/ide/idetools/start_abjad_ide.py", line 13, in start_abjad_ide
    abjad_ide._run(input_=input_)
  File "/Users/trevorbaca/Documents/ide/ide/idetools/AbjadIDE.py", line 216, in _run
    result)
  File "/Users/trevorbaca/Documents/ide/ide/idetools/AssetController.py", line 237, in _handle_input
    self._command_to_method[result]()
  File "/Users/trevorbaca/Documents/ide/ide/idetools/AssetController.py", line 759, in go_to_score_maker_files
    self._session._abjad_ide._maker_file_wrangler._run()
  File "/Users/trevorbaca/Documents/ide/ide/idetools/Wrangler.py", line 812, in _run
    self._handle_input(result)
  File "/Users/trevorbaca/Documents/ide/ide/idetools/AssetController.py", line 237, in _handle_input
    self._command_to_method[result]()
  File "/Users/trevorbaca/Documents/ide/ide/idetools/FileWrangler.py", line 147, in remove_files
    self._remove_assets()
  File "/Users/trevorbaca/Documents/ide/ide/idetools/Wrangler.py", line 764, in _remove_assets
    manager._remove()
  File "/Users/trevorbaca/Documents/ide/ide/idetools/PackageManager.py", line 661, in _remove
    with systemtools.TemporaryDirectoryChange(directory=self._path):
  File "/Users/trevorbaca/Documents/abjad/abjad/tools/systemtools/TemporaryDirectoryChange.py", line 29, in __enter__
    os.chdir(self.directory)
OSError: [Errno 2] No such file or directory: '/Users/trevorbaca/Documents/scores/krummzeit/krummzeit/makers/GlissandoSpecifier.py'
```

**Comment by trevorbaca** [comment]
Done 2015-04-15.
