### ISSUE TITLE
Fix null input at (new) menu

### ISSUE THREAD

**Issue by trevorbaca** [Abjad/ide#90]
Following stack trace happens in response to use enter nothing for file name:

```
Score (2015) - tools directory

   1: __init__.py
   2: ScoreTemplate.py
   3: TimeSignatureMaker.py

      copy (cp)
      new (new)
      remove (rm)
      rename (ren)

> new
File name]> 
Traceback (most recent call last):
  File "/Users/trevorbaca/Documents/abjad-ide/ide/scr/start-abjad-ide", line 8, in <module>
    abjad_ide._start(input_=input_)
  File "/Users/trevorbaca/Documents/abjad-ide/ide/tools/idetools/AbjadIDE.py", line 2018, in _start
    self._manage_directory(directory)
  File "/Users/trevorbaca/Documents/abjad-ide/ide/tools/idetools/AbjadIDE.py", line 1641, in _manage_directory
    self._handle_input(result)
  File "/Users/trevorbaca/Documents/abjad-ide/ide/tools/idetools/AbjadIDE.py", line 756, in _handle_input
    self._manage_directory(result)
  File "/Users/trevorbaca/Documents/abjad-ide/ide/tools/idetools/AbjadIDE.py", line 1641, in _manage_directory
    self._handle_input(result)
  File "/Users/trevorbaca/Documents/abjad-ide/ide/tools/idetools/AbjadIDE.py", line 736, in _handle_input
    self._manage_directory(path)
  File "/Users/trevorbaca/Documents/abjad-ide/ide/tools/idetools/AbjadIDE.py", line 1641, in _manage_directory
    self._handle_input(result)
  File "/Users/trevorbaca/Documents/abjad-ide/ide/tools/idetools/AbjadIDE.py", line 746, in _handle_input
    command(self._session.current_directory)
  File "/Users/trevorbaca/Documents/abjad-ide/ide/tools/idetools/AbjadIDE.py", line 3416, in go_to_previous_package
    self._manage_directory(directory)
  File "/Users/trevorbaca/Documents/abjad-ide/ide/tools/idetools/AbjadIDE.py", line 1641, in _manage_directory
    self._handle_input(result)
  File "/Users/trevorbaca/Documents/abjad-ide/ide/tools/idetools/AbjadIDE.py", line 746, in _handle_input
    command(self._session.current_directory)
  File "/Users/trevorbaca/Documents/abjad-ide/ide/tools/idetools/AbjadIDE.py", line 3401, in go_to_next_package
    self._manage_directory(directory)
  File "/Users/trevorbaca/Documents/abjad-ide/ide/tools/idetools/AbjadIDE.py", line 1641, in _manage_directory
    self._handle_input(result)
  File "/Users/trevorbaca/Documents/abjad-ide/ide/tools/idetools/AbjadIDE.py", line 746, in _handle_input
    command(self._session.current_directory)
  File "/Users/trevorbaca/Documents/abjad-ide/ide/tools/idetools/AbjadIDE.py", line 3506, in go_to_tools_directory
    self._manage_directory(directory)
  File "/Users/trevorbaca/Documents/abjad-ide/ide/tools/idetools/AbjadIDE.py", line 1641, in _manage_directory
    self._handle_input(result)
  File "/Users/trevorbaca/Documents/abjad-ide/ide/tools/idetools/AbjadIDE.py", line 746, in _handle_input
    command(self._session.current_directory)
  File "/Users/trevorbaca/Documents/abjad-ide/ide/tools/idetools/AbjadIDE.py", line 3856, in new
    self._make_file(directory)
  File "/Users/trevorbaca/Documents/abjad-ide/ide/tools/idetools/AbjadIDE.py", line 1080, in _make_file
    file_name = self._coerce_name(directory, file_name)
  File "/Users/trevorbaca/Documents/abjad-ide/ide/tools/idetools/AbjadIDE.py", line 154, in _coerce_name
    name = self._to_classfile_name(name)
  File "/Users/trevorbaca/Documents/abjad-ide/ide/tools/idetools/AbjadIDE.py", line 2077, in _to_classfile_name
    assert self._is_classfile_name(name), repr(name)
AssertionError: '.py'
```

**Comment by trevorbaca** [comment]
Fixed sometime in fall 2016.
