### ISSUE TITLE
Protect string input for "map"

### ISSUE THREAD

**Issue by trevorbaca** [Abjad/ide#95]
Example:

```
Score (2015) - etc directory

   1: notes.txt
   2: to-do.txt

      copy (cp)
      new (new)
      remove (rm)
      rename (ren)

> new
File name]> map.txt
Traceback (most recent call last):
  File "/Users/trevorbaca/Documents/abjad-ide/ide/scr/start-abjad-ide", line 8, in <module>
    abjad_ide._start(input_=input_)
  File "/Users/trevorbaca/Documents/abjad-ide/ide/tools/idetools/AbjadIDE.py", line 2018, in _start
    self._manage_directory(directory)
  File "/Users/trevorbaca/Documents/abjad-ide/ide/tools/idetools/AbjadIDE.py", line 1641, in _manage_directory
    self._handle_input(result)
  File "/Users/trevorbaca/Documents/abjad-ide/ide/tools/idetools/AbjadIDE.py", line 756, in _handle_input
    self._manage_directory(result)
  File "/Users/trevorbaca/Documents/abjad-ide/ide/tools/idetools/AbjadIDE.py", line 1641, in _manage_directory
    self._handle_input(result)
  File "/Users/trevorbaca/Documents/abjad-ide/ide/tools/idetools/AbjadIDE.py", line 746, in _handle_input
    command(self._session.current_directory)
  File "/Users/trevorbaca/Documents/abjad-ide/ide/tools/idetools/AbjadIDE.py", line 3371, in go_to_etc_directory
    self._manage_directory(directory)
  File "/Users/trevorbaca/Documents/abjad-ide/ide/tools/idetools/AbjadIDE.py", line 1641, in _manage_directory
    self._handle_input(result)
  File "/Users/trevorbaca/Documents/abjad-ide/ide/tools/idetools/AbjadIDE.py", line 746, in _handle_input
    command(self._session.current_directory)
  File "/Users/trevorbaca/Documents/abjad-ide/ide/tools/idetools/AbjadIDE.py", line 3856, in new
    self._make_file(directory)
  File "/Users/trevorbaca/Documents/abjad-ide/ide/tools/idetools/AbjadIDE.py", line 1077, in _make_file
    file_name = getter._run(io_manager=self._io_manager)
  File "/Users/trevorbaca/Documents/abjad-ide/ide/tools/idetools/Getter.py", line 212, in _run
    self._present_prompts(include_chevron=self._include_chevron)
  File "/Users/trevorbaca/Documents/abjad-ide/ide/tools/idetools/Getter.py", line 207, in _present_prompts
    self._present_prompt(include_chevron=include_chevron)
  File "/Users/trevorbaca/Documents/abjad-ide/ide/tools/idetools/Getter.py", line 196, in _present_prompt
    self._evaluate_input(directive, namespace)
  File "/Users/trevorbaca/Documents/abjad-ide/ide/tools/idetools/Getter.py", line 106, in _evaluate_input
    input_, namespace, namespace)
  File "<string>", line 1, in <module>
AttributeError: 'builtin_function_or_method' object has no attribute 'txt'
```

**Comment by trevorbaca** [comment]
Done 2016-12-11.
